version: "3"
services:
    mongo:
        image: 'mongo:latest'
        restart: always
        container_name: mongo
        ports:
            - '27017:27017'
        volumes:
            - './mongo/data:/data/db'  
        networks:
            - app-network
    api-tier:
        container_name: cc-api-tier
        restart: always
        build:
            context: ./api-tier
            dockerfile: Dockerfile
        ports:
            - '5000:5000'
        depends_on:
            - mongo
        networks:
            - app-network
    frontend-tier:   
        container_name: cc-frontend-tier
        restart: always
        build:
            context: ./frontend-tier
            dockerfile: Dockerfile
        ports:
            - '3000:3000'
        networks:
            - app-network                    


networks:
        app-network:
            driver: bridge